#+OPTIONS: toc:1
* Simulation
** [[http://pub.ist.ac.at/group_wojtan/projects/2013_Ando_HALSoTM/download/tetflip.pdf][Highly Adaptive Liquid Simulations on Tetrahedral Meshes]]
   This is basically an application of many different methods used fluid mechanics before it. With the addition of formulating the grid as
   a set of tets that can have variable sizes. Should look further into the boundary conditions. Otherwise, standard FLIP/PIC use.
** [[https://arxiv.org/abs/1408.1118][Spoke-Darts for High-Dimensional Blue-Noise Sampling]]
   Useful in which applications? Most configuration exploration problems a level of sampling. Why is blue noise the right choice here?
   It makes sense that a robust sampling method is useful, how can this be applied in ways to adapt over a preliminary choice of samples?
   Constrain the algorithm based on the application?
** [[https://lgg.epfl.ch/publications/2014/ProjectiveDynamics//paper.pdf][Projective Dynamics: Fusing Constraint Projections for Fast Simulation]]
   What's the insight of the integrator here? Maybe that constraints can be synthesized in smarter ways so that they are easier to compute

** [[http://www.pnas.org/content/110/45/18327][Simulation as an engine of physical scene understanding]]
   The simulation here is not very complex, and probably only simulates simple scenes. Though the main construction of the simulation seems
   to be pretty interesting. Generally using a stochastic approach-using one run of the simulation as a sample in the probabilistic domain
   
   "The IPE performs prediction by simulation and incorporates uncertainty about the scene by treating its simulation runs as statistical samples"

** [[https://dl.acm.org/citation.cfm?doid=3151031.3153420][Stabilizing Integrators for Real-Time Physics]]
   The main insight is that while a symplectic integrator oscillates around an energy. It is possible to blend in another integrator that either injects or dampens energy from the system.
** [[http://graphics.pixar.com/library/StableElasticity/paper.pdf][Stable Neo-Hookean Flesh Simulation]]
   This will be useful in skin simulation. Soft body dynamics will also need this. Real-time prioritizes stability over accuracy?
** [[https://www.seas.upenn.edu/~cffjiang/research/async/fang2018async.pdf][A Temporally Adaptive Material Point Method with Regional Time Stepping]]
   The main insight is that you can check to see if the energy is going to managable, in which case, you can change the time step for a block so that it only needs to be updated based on the energy in it. The tricky part is the boundary of two blocks with different time steps. This can be solved by assumming the block is constant for the smaller time step block's boundary, by "duplicating" the boundary box and using that to update.
* Configuration in robotics
** [[http://www.roboticsproceedings.org/rss01/p15.pdf][Towards Optimal Configuration Space Sampling]]
   Another question of how to properly sample the configuration space so that you can obtain optimal path planning.
** [[https://arxiv.org/pdf/1502.02474.pdf][Planning for robotic exploration based on forward simulation]]

* Deep Learning assistance
** [[https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8202133][Domain Randomization for Transferring Deep Neural Networks from Simulation to the Real World]]
   Only concerned with the domain randomization problem here. More like is there a way to explore/assess coverage? This looks more like the beginning
   of this idea of domain exploration.

* Rendering
** [[https://link.springer.com/chapter/10.1007%2F978-3-319-10584-0_11][Differentiable Rendering]]
** [[https://dl.acm.org/citation.cfm?id=2766930][Variance analysis for Monte Carlo integration]]
   Talks about a language for assessing the different sampling strategies for raytracing

** [[http://delivery.acm.org/10.1145/2190000/2185554/a58-jakob.pdf?ip=128.237.218.193&id=2185554&acc=ACTIVE%20SERVICE&key=A792924B58C015C1%2E5A12BE0369099858%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&__acm__=1541003952_6cfb7bcc45fca10e28119c2c4ef20bb9][Manifold Exploration: A Markov Chain Monte Carlo Technique for Rendering Scenes with Difficult Specular Transport]]

** Notes about Metropolis Light Transport
   - Relies on having BDPT and regular PT to see the sampling mechanisms
* Generic Sampling Methods
** [[http://proceedings.mlr.press/v22/brubaker12/brubaker12.pdf][Family of MCMC Methods on Implicitly Defined Manifolds]]
   - It seems that MCMC really mostly used when we need to actually evaluate _f(x)_

* Things to do
** DONE Look at the Picture Paper by Tenenbaum
   CLOSED: [2018-10-31 Wed 13:02]
*** Questions
    - Elliptical Slice Proposals
    - MCMC approximation algorithm
    - It seems like we need some sort of prior classifier for Picture to work. Does it need to be related to the actual task?
** DONE Look at the Stable integrator paper
   CLOSED: [2018-10-31 Wed 13:02]
   The main insight is that we can use backward and forward euler to attenuate the oscillations in energy from a symplectic integrator.

** DONE Download Mitsuba Renderer
   CLOSED: [2018-10-31 Wed 13:02]
   Think more about the project and whether or not its something I really want to commit to.
** TODO Look more into inverse rendering (MLT Potential)
