* Preliminary Research into probable systems
** Stochastic Modeling of Physical Systems
*** [[https://hal.archives-ouvertes.fr/hal-01516295/document][Uncertainty Quantification]]
*** [[https://www.math.uchicago.edu/~lawler/finbook2.pdf][Stochastic Calculus]]


* Thoughts on Adaptive Imaging techniques
The goal of this project is to develop a framework for deciding on how to continuously adapt sensing strategies to capture shape information based on information already captured. 
Dynamically reconciling the different noise characteristics from different sensor modalities helps to identify useful strategies for shape capture.

The proposal is to construct a probabilistic representation of shape that can encode the different sensor modalities and their respective error models. 
By having noise as a principal component of shape, it will be easier to discern what is known about the subject and scene.
Having a dynamic model of what is and is not known allows for reasoning about optimal strategies for the next round of capture.

First steps in this project would be to study how different noise characteristics interact with each other in different surface reconstruction environments like room capture and high fidelity recovery.
