* Preliminary Research into probable systems
** Stochastic Modeling of Physical Systems
*** [[https://hal.archives-ouvertes.fr/hal-01516295/document][Uncertainty Quantification]]
*** [[https://www.math.uchicago.edu/~lawler/finbook2.pdf][Stochastic Calculus]]


* Thoughts on Adaptive Imaging techniques
The goal of this project is to develop a framework for deciding on how to continuously capture shape information based on what is already known about the subject being captured. 
Recognizing the different noise characteristics from different sensor modalities dynamically allows for readapting the sensing strategy to better capture the shape data of the subject.
This requires understanding how the noise characteristics of each sensor modality interacts with each other and understanding what strategies can be employed to minimize the resulting variance.

The proposal is to construct a probabilistic representation of shape that can encode the different sensor modalities and their respective error models. 
By having noise as a principal component of shape, it will be easier to discern what is known about the subject and scene.
Having a dynamic model of what is and is not known allows for reasoning about optimal strategies for the next round of capture.

First steps in this project would be to study how different noise characteristics interact with each other in different surface reconstruction environments like room capture and high fidelity recovery.
